services:
  paddlex:
    image: paddlex-ocr:latest
    container_name: paddlex-ocr
    ports:
      - "25601:8080"
    volumes:
      - /opt/qzwb/paddlex-ocr/paddlex:/root/.paddlex
      - /opt/qzwb/paddlex-ocr/pipeline.yaml:/data/pipeline.yaml
    environment:
      DISABLE_MODEL_SOURCE_CHECK: "True"
      PIPELINE_FILE: /data/pipeline.yaml
      DEFAULT_PIPELINE: OCR
      DEVICE: cpu
      PORT: 8080
    restart: unless-stopped
